### ISSUE TITLE
Cursor and highlights become invisible when using the addon.

### ISSUE THREAD

**Issue by mzso** [117649/AdvancedLocationbar#4]
Hello!

This a fair bit of an annoyance and usability issue.

So I often type something and then select an item by navigating up/down, in which case the url is fed to the urlbar. Then I use the keyboard to edit the url.
But this doesn't work well with this addon. The cursor and text highlighting becomes and remains invisible. Though they do take effect I can invisibly navigate highlight then type/delete and it's performed as if both were visible.

It seems like the highlights only appear if I hover the mouse cursor above the urlbar. So even if I use the mouse to select text in it, when I drag the cursor away it disappears, and only reappears when I hover again.

The only option I have enabled is the linkification via ctrl/alt/shift.

**Comment by 117649** [comment]
Will fix in due time.

**Comment by mzso** [comment]
Thanks. Will you make note of it here, or should I keep watch for a new release?

**Comment by 117649** [comment]
https://github.com/117649/AdvancedLocationbar2/releases/tag/1.2.1.7

**Comment by mzso** [comment]
[**@117649**](https://github.com/117649) commented on [2021. szept. 2. 05:53 CEST](https://github.com/117649/AdvancedLocationbar2/issues/4#issuecomment-911127270 "2021-09-02T03:53:14Z - Replied by Github Reply Comments"):
> [https://github.com/117649/AdvancedLocationbar2/releases/tag/1.2.1.7](https://github.com/117649/AdvancedLocationbar2/releases/tag/1.2.1.7)

Thanks! Nice quick action.

**Comment by mzso** [comment]
Hmmm. It seems like sometimes the cart/highlights still fail to appear. And I need to move, hover the mouse cursor.
Wouldn't it it make sense to completely disable URL bar styling* as long as the focus is there? (including the URL bar results)

*Which I guess is the cause of the issue.

**Comment by 117649** [comment]
> 
> 
> Hmmm. It seems like sometimes the cart/highlights still fail to appear. And I need to move, hover the mouse cursor.
> Wouldn't it it make sense to completely disable URL bar styling* as long as the focus is there? (including the URL bar results)
> 
> *Which I guess is the cause of the issue.

That should already be the case.
I've re-uploaded file.
Check if you updated to newest version.
And provide detail on how to reproduce the problem.

**Comment by mzso** [comment]
[**@117649**](https://github.com/117649) commented on [2021. szept. 6. 12:40 CEST](https://github.com/117649/AdvancedLocationbar2/issues/4#issuecomment-913545101 "2021-09-06T10:40:38Z - Replied by Github Reply Comments"):
> > Hmmm. It seems like sometimes the cart/highlights still fail to appear. And I need to move, hover the mouse cursor.  
> > Wouldn't it it make sense to completely disable URL bar styling\* as long as the focus is there? (including the URL bar results)
> > 
> > \*Which I guess is the cause of the issue.
> 
> That should already be the case.  
> I've re-uploaded file.  
> Check if you updated to newest version.  
> And provide detail on how to reproduce the problem.

So the file was wrong? Anyway I'll reinstall it. See what happens.
