### ISSUE TITLE
No install instructions for Linux (or Mac I guess but who uses firefox on Mac)

### ISSUE THREAD

**Issue by Hate9** [117649/AdvancedLocationbar#5]
The installer is an .xpi, a windows installer file. If this can install to Firefox via Wine, please make this apparent - otherwise, please provide manual installation instructions or a Linux installer.

**Comment by 117649** [comment]
Em, Huh?
 You just got the concept so wrong.
[.xpi is nothing but .zip renamed .](https://en.wikipedia.org/wiki/XPInstall)
The rest of your post were just meaningless.
I'm just close this.

**Comment by Hate9** [comment]
oh right, I got it confused with msi. duhr.
