### ISSUE TITLE
Doesn't work on FF130 dev edition anymore. Can it be fixed?

### ISSUE THREAD

**Issue by mzso** [117649/AdvancedLocationbar#6]
It seems like this was broken by FF changes and is not working anymore.  Can it be fixed?

**Comment by 117649** [comment]
No new release will be made for this repo.

This is fixed months a go.

**Comment by mzso** [comment]
Kind of weird that I had to zip the folder myself, but okay.

**Comment by mzso** [comment]
> No new release will be made for this repo.
> 

I don't understand the reason. People who might be looking for it will only find [a version that's broken already](https://github.com/117649/AdvancedLocationbar2/releases/tag/1.2.1.7).

If it's fixed anyway, why not make it accessible?

**Comment by 117649** [comment]
> > No new release will be made for this repo.
> 
> I don't understand the reason. People who might be looking for it will only find [a version that's broken already](https://github.com/117649/AdvancedLocationbar2/releases/tag/1.2.1.7).
> 
> If it's fixed anyway, why not make it accessible?

Because there was no people but me.
![image](https://github.com/user-attachments/assets/01ebdb4c-7df7-462d-b4b3-727b4876b0e3)

**Comment by 117649** [comment]
https://github.com/117649/AdvancedLocationbar2/releases/tag/dev-build

Setup an auto release process.
Nothing is guaranteed though.
